---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pg-operator
  namespace: apps
spec:
  interval: 1m
  releaseName: pg-operator
  chart:
    spec:
      chart: pg-operator
      sourceRef:
        name: percona
        kind: HelmRepository
      reconcileStrategy: ChartVersion
      version: "2.6.0"
      interval: 5m0s
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values: {}
