---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: krakend
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: config-krakend
  files: ['krakend.json=config/krakend.json']
