---
apiVersion: v1
kind: Namespace
metadata:
  name: kubernetes-ui
  labels:
    app.kubernetes.io/name: kubernetes-ui
    app.kubernetes.io/instance: kubernetes-ui
    app.kubernetes.io/env: home

---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/env: home

---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  labels:
    app.kubernetes.io/name: metallb-system
    app.kubernetes.io/instance: metallb-system
    app.kubernetes.io/env: home

---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn
  labels:
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/instance: longhorn
    app.kubernetes.io/env: home

---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/env: home

---
apiVersion: v1
kind: Namespace
metadata:
  name: postgresql
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: postgresql
    app.kubernetes.io/env: home

---
apiVersion: v1
kind: Namespace
metadata:
  name: immich
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/instance: immich
    app.kubernetes.io/env: home

---
apiVersion: v1
kind: Namespace
metadata:
  name: tesla
  labels:
    app.kubernetes.io/name: tesla
    app.kubernetes.io/instance: tesla
    app.kubernetes.io/env: home

---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/env: home
