---
apiVersion: v1
kind: Namespace
metadata:
  name: kubernetes-dashboard
  labels:
    app.kubernetes.io/name: kubernetes-dashboard
    app.kubernetes.io/instance: kubernetes-dashboard
    app.kubernetes.io/env: home

---
apiVersion: v1
kind: Namespace
metadata:
  name: portainer
  labels:
    app.kubernetes.io/name: portainer
    app.kubernetes.io/instance: portainer
    app.kubernetes.io/env: home

---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/env: home

---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  labels:
    app.kubernetes.io/name: metallb-system
    app.kubernetes.io/instance: metallb-system
    app.kubernetes.io/env: home

---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn
  labels:
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/instance: longhorn
    app.kubernetes.io/env: home

---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/instance: cert-manager
    app.kubernetes.io/env: home

---
apiVersion: v1
kind: Namespace
metadata:
  name: shared
  labels:
    app.kubernetes.io/name: shared
    app.kubernetes.io/instance: shared
    app.kubernetes.io/env: home

---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/env: home

---
apiVersion: v1
kind: Namespace
metadata:
  name: immich
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/instance: immich
    app.kubernetes.io/env: home

---
apiVersion: v1
kind: Namespace
metadata:
  name: teslamate
  labels:
    app.kubernetes.io/name: teslamate
    app.kubernetes.io/instance: teslamate
    app.kubernetes.io/env: home

---
apiVersion: v1
kind: Namespace
metadata:
  name: jellyfin
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/instance: jellyfin
    app.kubernetes.io/env: home
