---
apiVersion: v1
kind: Secret
metadata:
  name: auth-minio
  namespace: monitoring
type: Opaque
data:
  MINIO_SERVER_ROOT_USER: c3lz
  MINIO_SERVER_ROOT_PASSWORD: WFdSRXFvU2llSjBrOEJZTXRKUzM1dWFsUEE=
  MINIO_SERVER_HOST: bWluaW8ubW9uaXRvcmluZy5zdmM=
  MINIO_SERVICE_PORT: OTAwMA==
