---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-home
  labels:
    env: home
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: skullfighter6@gmail.com
    privateKeySecretRef:
      name: letsencrypt-home
    solvers:
    - http01:
        ingress:
          class: nginx
