---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-base
  namespace: flux-system
spec:
  suspend: false
  interval: 10m0s
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: kubernetes/resources/prod/00 - base
  prune: true
  wait: true
  timeout: 35m

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-dependencies
  namespace: flux-system
spec:
  suspend: false
  interval: 10m0s
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: kubernetes/resources/prod/01 - dependencies
  prune: true
  wait: true
  timeout: 35m
  dependsOn:
    - name: infra-base

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-post-dependencies
  namespace: flux-system
spec:
  suspend: false
  interval: 10m0s
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: kubernetes/resources/prod/02 - post-dependencies
  prune: true
  wait: true
  timeout: 35m
  dependsOn:
    - name: infra-base
    - name: infra-dependencies

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: event-tracking
  namespace: flux-system
spec:
  suspend: false
  interval: 10m0s
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: kubernetes/resources/prod/03 - event-tracking
  prune: true
  wait: true
  timeout: 35m
  dependsOn:
    - name: infra-base
    - name: infra-dependencies
    - name: infra-post-dependencies
