---
apiVersion: v1
kind: Secret
metadata:
  name: auth-minio
  namespace: velero
type: Opaque
data:
  credentials: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkID0gc3lzCmF3c19zZWNyZXRfYWNjZXNzX2tleSA9IFhXUkVxb1NpZUowazhCWU10SlMzNXVhbFBB
