---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: velero
  namespace: velero
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-home
    kubernetes.io/ingress.class: nginx
  labels:
    app: velero
    env: home
spec:
  tls:
  - hosts:
    - velero.k8s.iaminyourpc.xyz
    secretName: tls-velero-k8s-iaminyourpc-xyz
  rules:
  - host: velero.k8s.iaminyourpc.xyz
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: velero
            port:
              number: 8085
