---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: data-postgresql
  namespace: immich
spec:
  refreshInterval: 5m0s
  secretStoreRef:
    name: home-vault
    kind: ClusterSecretStore
  target:
    name: data-postgresql
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: home/immich/data-postgresql
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
