---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-exporter
  namespace: monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9594"
  labels:
    env: home
spec:
  type: ClusterIP
  ports:
  - name: jellyfin-exporter
    port: 9594
    targetPort: 9594
  selector:
    app: jellyfin-exporter
