---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: script-vault-auto-backup
  files: ['backup.py=../../scripts/utils/backup.py']
- name: script-vault-auto-unseal
  files: ['unseal.sh=../../scripts/utils/vault/unseal.sh']
- name: script-vault-setup
  files: ['setup.sh=../../scripts/utils/vault/setup.sh']
- name: data-vault-policy-external-secrets
  files: ['external-secrets.hcl=../../scripts/utils/vault/policies/external-secrets.hcl']
