---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: script-vault-auto-backup
  files: ['backup.py=scripts/backup.py']
- name: script-vault-auto-unseal
  files: ['unseal.sh=scripts/unseal.sh']
- name: script-vault-setup
  files: ['setup.sh=scripts/setup.sh']
- name: data-vault-policy-external-secrets
  files: ['external-secrets.hcl=policies/external-secrets.hcl']
# - name: dummy-test
#   files: ['test.sh=../../test.sh']
