---
apiVersion: v1
kind: Service
metadata:
  name: public-key-hoster
  namespace: home-assistant
  labels:
    env: home
spec:
  type: ClusterIP
  ports:
  - name: public-key-hoster
    port: 8080
    targetPort: 8080
  selector:
    app: public-key-hoster

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: public-key-hoster
  namespace: home-assistant
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-home
    kubernetes.io/ingress.class: nginx
  labels:
    app: public-key-hoster
    env: home
spec:
  tls:
  - hosts:
    - car.home.k8s.iaminyourpc.xyz
    secretName: tls-car-home-k8s-iaminyourpc-xyz
  rules:
  - host: car.home.k8s.iaminyourpc.xyz
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: public-key-hoster
            port:
              number: 8080
