---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: data-postgresql-shared-teslamate-teslamate
  namespace: monitoring
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: in-cluster-shared
    kind: ClusterSecretStore
  target:
    name: data-postgresql-shared-teslamate-teslamate
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: data-postgresql-shared-teslamate-teslamate
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: data-postgresql-shared-teslamate-teslamate
  namespace: teslamate
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: in-cluster-shared
    kind: ClusterSecretStore
  target:
    name: data-postgresql-shared-teslamate-teslamate
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: data-postgresql-shared-teslamate-teslamate
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
