---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-shared-pg-cluster-ca-cert
  namespace: teslamate
spec:
  refreshInterval: 5m0s
  secretStoreRef:
    name: in-cluster-shared
    kind: ClusterSecretStore
  target:
    name: postgresql-shared-pg-cluster-ca-cert
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: postgresql-shared-pg-cluster-ca-cert
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
