---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-media-windows-data
  namespace: radarr
  labels:
    app: radarr
    env: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
  storageClassName: manual
  volumeName: media-windows-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  namespace: radarr
  labels:
    app: radarr
    env: home
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
