---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-media-windows-data
  labels:
    app: radarr
    env: home
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /media/martin/Windows Data
    type: Directory
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-media-windows-data
  namespace: radarr
  labels:
    app: radarr
    env: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
  storageClassName: manual
  volumeName: radarr-media-windows-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  namespace: radarr
  labels:
    app: radarr
    env: home
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
