---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: control-ui
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: config-control-ui
  envs: ['config.env']
