---
apiVersion: v1
kind: Secret
metadata:
  labels:
    k8s-app: kubernetes-dashboard
  name: kubernetes-dashboard-certs
  namespace: kubernetes-dashboard
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  labels:
    k8s-app: kubernetes-dashboard
  name: kubernetes-dashboard-csrf
  namespace: kubernetes-dashboard
type: Opaque
data:
  csrf: ""

---
apiVersion: v1
kind: Secret
metadata:
  labels:
    k8s-app: kubernetes-dashboard
  name: kubernetes-dashboard-key-holder
  namespace: kubernetes-dashboard
type: Opaque

---
kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    k8s-app: kubernetes-dashboard
  name: kubernetes-dashboard-settings
  namespace: kubernetes-dashboard

---
apiVersion: v1
kind: Secret
metadata:
  name: auth-kubernetes-dashboard
  namespace: kubernetes-dashboard
  labels:
    env: home
    htpasswd: kubernetes-dashboard
type: Opaque
data:
  auth: c3lzOiRhcHIxJHFnZW81Y3diJG5xRGdGbE1EeWF2UE0xZ3Z5ZUVpcDA=
