---
apiVersion: v1
kind: Secret
metadata:
  labels:
    k8s-app: kubernetes-ui
  name: kubernetes-ui-certs
  namespace: kubernetes-ui
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  labels:
    k8s-app: kubernetes-ui
  name: kubernetes-ui-csrf
  namespace: kubernetes-ui
type: Opaque
data:
  csrf: ""

---
apiVersion: v1
kind: Secret
metadata:
  labels:
    k8s-app: kubernetes-ui
  name: kubernetes-ui-key-holder
  namespace: kubernetes-ui
type: Opaque

---
kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    k8s-app: kubernetes-ui
  name: kubernetes-ui-settings
  namespace: kubernetes-ui

---
apiVersion: v1
kind: Secret
metadata:
  name: kubernetes-ui-auth
  namespace: kubernetes-ui
  labels:
    env: home
    htpasswd: kubernetes-ui
type: Opaque
data:
  auth: c3lzOiRhcHIxJHFnZW81Y3diJG5xRGdGbE1EeWF2UE0xZ3Z5ZUVpcDA=
