---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kubernetes-ui
  namespace: kubernetes-ui
  labels:
    env: home
spec:
  interval: 1m
  releaseName: kubernetes-dashboard
  chart:
    spec:
      chart: kubernetes-dashboard
      sourceRef:
        kind: HelmRepository
        name: kubernetes
      reconcileStrategy: ChartVersion
      version: 7.12.0
      interval: 5m0s
