---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: kubernetes-ui
  name: kubernetes-ui
  namespace: kubernetes-ui
spec:
  ports:
    - name: https
      port: 443
      targetPort: 8443
    - name: http
      port: 80
      targetPort: 9090
  selector:
    k8s-app: kubernetes-ui

---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: dashboard-metrics-scraper
  name: dashboard-metrics-scraper
  namespace: kubernetes-ui
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    k8s-app: dashboard-metrics-scraper

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubernetes-ui
  namespace: kubernetes-ui
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-home
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: kubernetes-ui-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
  labels:
    app: kubernetes-ui
    env: home
spec:
  tls:
  - hosts:
    - k8s.iaminyourpc.xyz
    secretName: tls-k8s-iaminyourpc-xyz
  rules:
  - host: k8s.iaminyourpc.xyz
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: kubernetes-ui
            port:
              number: 80
