---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shared
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: script-pg-auto-backup
  files: ['backup.py=scripts/backup.py']
