---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prestashop
  namespace: hostfabtech
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-home
    kubernetes.io/ingress.class: nginx
  labels:
    app: prestashop
    env: home
spec:
  tls:
  - hosts:
    - shop.hostfabtech.xyz
    secretName: shop-hostfabtech-xyz
  rules:
  - host: shop.hostfabtech.xyz
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: prestashop
            port:
              number: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prestashop-filebrowser
  namespace: hostfabtech
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-home
    kubernetes.io/ingress.class: nginx
  labels:
    app: prestashop-filebrowser
    env: home
spec:
  tls:
  - hosts:
    - files.shop.hostfabtech.xyz
    secretName: files-shop-hostfabtech-xyz
  rules:
  - host: files.shop.hostfabtech.xyz
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: prestashop-filebrowser
            port:
              number: 30081
