---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql-shared
  namespace: shared
spec:
  interval: 1m
  releaseName: postgresql-shared
  chart:
    spec:
      chart: pg-db
      sourceRef:
        name: percona
        kind: HelmRepository
      reconcileStrategy: ChartVersion
      version: "2.6.0"
      interval: 5m0s
  values:
    image: perconalab/percona-postgresql-operator:main-ppg17-postgres
    postgresVersion: 17
    proxy:
      pgBouncer:
        replicas: 1
        config:
          global:
            client_tls_sslmode: allow
    instances:
    - name: shared
      replicas: 1
      dataVolumeClaimSpec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
    users:
    - name: teslamate
      secretName: data-postgresql-shared-teslamate
      databases:
      - teslamate
      options: "SUPERUSER"
    - name: monitoring-grafana
      secretName: data-postgresql-shared-monitoring-grafana
      databases:
      - monitoring-grafana
      options: "SUPERUSER"
