---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: in-cluster-shared
  annotations:
    external-secrets.io/disable-maintenance-checks: "true"
spec:
  provider:
    kubernetes:
      remoteNamespace: shared
      server:
        url: "https://kubernetes.default"
        caProvider:
          namespace: shared
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: external-secrets-shared
          namespace: shared
