---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: values-ingress-nginx
  files: ['values.yaml']
