---
apiVersion: v1
kind: Service
metadata:
  name: portainer-agent
  namespace: portainer
spec:
  selector:
    app: portainer-agent
  ports:
    - name: http
      protocol: TCP
      port: 9001
      targetPort: 9001

---
apiVersion: v1
kind: Service
metadata:
  name: portainer-agent-headless
  namespace: portainer
spec:
  clusterIP: None
  selector:
    app: portainer-agent

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portainer-agent
  namespace: portainer
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-home
    kubernetes.io/ingress.class: nginx
  labels:
    app: portainer-agent
    env: home
spec:
  tls:
  - hosts:
    - portainer-agent.k8s.iaminyourpc.xyz
    secretName: tls-portainer-agent-k8s-iaminyourpc-xyz
  rules:
  - host: portainer-agent.k8s.iaminyourpc.xyz
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: portainer-agent
            port:
              number: 9001
