---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: data-connector-ml
  namespace: fetch-api
spec:
  refreshInterval: 5m0s
  secretStoreRef:
    name: home-vault
    kind: ClusterSecretStore
  target:
    name: data-connector-ml
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: home/fetch-api/connectors/data-connector-ml
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
