---
apiVersion: v1
kind: Service
metadata:
  name: connector-ml
  namespace: fetch-api
  labels:
    env: home
spec:
  type: ClusterIP
  ports:
  - name: connector-ml
    port: 9069
    targetPort: 9069
  selector:
    app: connector-ml
