---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

configurations:
- kustomizeconfig.yaml

configMapGenerator:
- name: release-values
  files:
  - ../../../helm/04-monitoring/grafana/values.yaml

resources:
- resources/provisioning/datasources.yaml
- resources/network.yaml
- resources/data.yaml
- resources/release.yaml
