---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jellyfin
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: values-jellyfin
  files: ['values.yaml']
