---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: data-vault-sensitive
  namespace: vault
spec:
  refreshInterval: 5m0s
  secretStoreRef:
    name: home-vault
    kind: ClusterSecretStore
  target:
    name: data-vault-sensitive
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: home/vault/data-vault-sensitive
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
