---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: glance
  namespace: glance
  labels:
    app: glance
    env: home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glance
  template:
    metadata:
      labels:
        app: glance
        env: home
    spec:
      restartPolicy: Always
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
          type: File
      - name: assets-glance
        configMap:
          name: assets-glance
      - name: config-glance-glance
        # configMap:
        #   name: config-glance-glance
        hostPath:
          path: /home/martin/stuff/home-k8s/config/glance/config/glance.yml
          type: File
      - name: config-glance-home
        configMap:
          name: config-glance-home
      containers:
      - name: glance
        image: glanceapp/glance:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        - name: assets-glance
          mountPath: /app/assets
        - name: config-glance-glance
          # mountPath: /app/config/glance.yml
          # subPath: glance.yml
          mountPath: /app/config/glance.yml
          subPath: glance.yml
          readOnly: true
        - name: config-glance-home
          mountPath: /app/config/home.yml
          subPath: home.yml
        env:
        - name: MY_SECRET_TOKEN
          valueFrom:
            secretKeyRef:
              name: data-glance
              key: MY_SECRET_TOKEN
