---
apiVersion: v1
kind: Service
metadata:
  name: glance
  namespace: glance
  labels:
    env: home
spec:
  type: ClusterIP
  ports:
  - name: glance
    port: 8080
    targetPort: 8080
  selector:
    app: glance

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: glance
  namespace: glance
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-home
    kubernetes.io/ingress.class: nginx                  # home, # Dankata, # Marina/Zhelezhnitsa
    nginx.ingress.kubernetes.io/whitelist-source-range: "10.8.0.0/24,92.247.208.224/32,87.243.107.94/32,151.237.55.238/32"
  labels:
    app: glance
    env: home
spec:
  tls:
  - hosts:
    - dash.iaminyourpc.xyz
    secretName: tls-dash-iaminyourpc-xyz
  rules:
  - host: dash.iaminyourpc.xyz
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: glance
            port:
              number: 8080
