---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: data-github-actions
  namespace: github
spec:
  refreshInterval: 5m0s
  secretStoreRef:
    name: home-vault
    kind: ClusterSecretStore
  target:
    name: data-github-actions
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: home/github/data-github-actions
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
