---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-longhorn
  namespace: longhorn
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: home-vault
    kind: ClusterSecretStore
  target:
    name: auth-longhorn
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: home/longhorn/auth-longhorn
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
