---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
  namespace: immich
  labels:
    app: immich-server
    env: home
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: immich-server
  template:
    metadata:
      labels:
        app: immich-server
        env: home
    spec:
      serviceAccount: default
      serviceAccountName: default
      automountServiceAccountToken: true
      enableServiceLinks: true
      terminationGracePeriodSeconds: 30
      restartPolicy: Always
      volumes:
      - name: library
        persistentVolumeClaim:
          claimName: immich-server-photos
      containers:
      - name: immich-server
        image: ghcr.io/immich-app/immich-server:v2.1.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /api/server/ping
            port: 2283
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /api/server/ping
            port: 2283
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 1
        startupProbe:
          httpGet:
            path: /api/server/ping
            port: 2283
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 1
        ports:
        - containerPort: 2283
        volumeMounts:
        - name: library
          mountPath: /usr/src/app/upload
        env:
        - name: UPLOAD_LOCATION
          value: "/usr/src/app/upload/library"
        - name: IMMICH_MACHINE_LEARNING_URL
          value: "http://immich-machine-learning.immich.svc:3003"
        - name: IMMICH_IGNORE_MOUNT_CHECK_ERRORS
          value: "true"
        - name: IMMICH_TELEMETRY_INCLUDE
          value: "all"
        - name: REDIS_HOSTNAME
          value: "redis.immich.svc"
        - name: REDIS_PORT
          value: "6379"
        - name: DB_HOSTNAME
          value: "postgresql.immich.svc"
        - name: DB_DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: data-postgresql
              key: dbname
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: data-postgresql
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: data-postgresql
              key: password
