---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn
  labels:
    env: home
spec:
  interval: 1m
  releaseName: longhorn
  chart:
    spec:
      chart: longhorn
      sourceRef:
        kind: HelmRepository
        name: longhorn
      reconcileStrategy: ChartVersion
      version: 1.8.1
      interval: 5m0s
  values:
    persistence:
      defaultClassReplicaCount: 1
      defaultDataLocality: best-effort
      migratable: true
    defaultSettings:
      defaultReplicaCount: 1
    service:
      ui:
        type: ClusterIP
