---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn
  namespace: longhorn
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-home
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: longhorn-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
    nginx.ingress.kubernetes.io/server-snippet: |
      location /.well-known/acme-challenge/ {
        proxy_pass http://longhorn.k8s.iaminyourpc.xyz:30080;
      }
  labels:
    app: longhorn
    env: home
spec:
  tls:
  - hosts:
    - longhorn.k8s.iaminyourpc.xyz
    secretName: letsencrypt-home
  rules:
  - host: longhorn.k8s.iaminyourpc.xyz
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: longhorn-frontend
            port:
              number: 80
