---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: data-control-ui
  namespace: control-ui
spec:
  refreshInterval: 5m0s
  secretStoreRef:
    name: home-vault
    kind: ClusterSecretStore
  target:
    name: data-control-ui
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: home/control-ui/data-control-ui
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
