---
apiVersion: v1
kind: Service
metadata:
  name: control-ui
  namespace: control-ui
  labels:
    env: home
spec:
  type: ClusterIP
  ports:
  - name: control-ui
    port: 80
    targetPort: 80
  selector:
    app: control-ui

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: control-ui
  namespace: control-ui
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-home
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: auth-control-ui
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
  labels:
    app: control-ui
    env: home
spec:
  tls:
  - hosts:
    - control.k8s.iaminyourpc.xyz
    secretName: tls-control-k8s-iaminyourpc-xyz
  rules:
  - host: control.k8s.iaminyourpc.xyz
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: control-ui
            port:
              number: 80
