---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: config-grafana-datasources
  files: ['datasources.yaml']
- name: config-grafana-dashboards
  files: ['dashboards.yaml']
resources:
- dashboards
