---
apiVersion: v1
kind: Service
metadata:
  name: immich-server
  namespace: immich
  labels:
    env: home
spec:
  type: ClusterIP
  ports:
  - name: immich-server
    port: 2283
    targetPort: 2283
  selector:
    app: immich-server

---
apiVersion: v1
kind: Service
metadata:
  name: immich-api-metrics
  namespace: immich
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8081"
    prometheus.io/path: "/metrics"
  labels:
    env: home
spec:
  type: ClusterIP
  ports:
  - name: immich-api-metrics
    port: 8081
    targetPort: 8081
  selector:
    app: immich-server

---
apiVersion: v1
kind: Service
metadata:
  name: immich-microservices-metrics
  namespace: immich
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8082"
    prometheus.io/path: "/metrics"
  labels:
    env: home
spec:
  type: ClusterIP
  ports:
  - name: immich-microservices-metrics
    port: 8082
    targetPort: 8082
  selector:
    app: immich-server

---
apiVersion: v1
kind: Service
metadata:
  name: immich-machine-learning
  namespace: immich
  labels:
    env: home
spec:
  type: ClusterIP
  ports:
  - name: immich-machine-learning
    port: 3003
    targetPort: 3003
  selector:
    app: immich-machine-learning

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immich
  namespace: immich
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-home
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/client-body-buffer-size: 10G
    nginx.ingress.kubernetes.io/proxy-body-size: 10G
  labels:
    app: immich
    env: home
spec:
  tls:
  - hosts:
    - photos.k8s.iaminyourpc.xyz
    secretName: tls-photos-k8s-iaminyourpc-xyz
  rules:
  - host: photos.k8s.iaminyourpc.xyz
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: immich-server
            port:
              number: 2283
