---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-grafana
  namespace: monitoring
spec:
  refreshInterval: 5m0s
  secretStoreRef:
    name: home-vault
    kind: ClusterSecretStore
  target:
    name: auth-grafana
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: home/monitoring/auth-grafana
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
