---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin
  namespace: jellyfin
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-home
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/client-body-buffer-size: 10G
    nginx.ingress.kubernetes.io/proxy-body-size: 10G
  labels:
    app: jellyfin
    env: home
spec:
  tls:
  - hosts:
    - watch.k8s.iaminyourpc.xyz
    secretName: tls-watch-k8s-iaminyourpc-xyz
  rules:
  - host: watch.k8s.iaminyourpc.xyz
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: jellyfin
            port:
              number: 8096
