---
apiVersion: v1
kind: Secret
metadata:
  name: teslamate-auth
  namespace: apps
  labels:
    env: home
    htpasswd: teslamate
type: Opaque
data:
  auth: c3lzOiRhcHIxJHdhamt0ZGN4JHNEckNBaFVmY2s3T0l5dHFSUkI0VDA=
