---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: tesla
  labels:
    app: grafana
    env: home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
        env: home
    spec:
      volumes:
      - name: grafana-data
        persistentVolumeClaim:
          claimName: grafana
      containers:
      - name: grafana
        image: teslamate/grafana:latest
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: grafana-data
          mountPath: /var/lib/grafana
        env:
        - name: DATABASE_HOST
          value: postgresql.tesla.svc:5432
        - name: DATABASE_NAME
          value: teslamate
        - name: DATABASE_USER
          value: teslamate
        - name: DATABASE_PASS
          value: teslamate
