replicaCount: 1

persistentVolumeClaim:
  enabled: true

serviceDns:
  loadBalancerIP: 192.168.1.180
  port: 53
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer

admin:
  existingSecret: auth-pihole
  passwordKey: PIHOLE_PASSWORD
