replicaCount: 1

persistentVolumeClaim:
  enabled: true

serviceDns:
  loadBalancerIP: 192.168.1.180
  port: 53
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer

admin:
  existingSecret: auth-pihole
  passwordKey: PIHOLE_PASSWORD

adlists:
- https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
- https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/pro.txt
- https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/wildcard/popupads-onlydomains.txt
- https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt
