---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fetch-api
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: script-health-probe
  files: ['health-probe.py=scripts/health-probe.py']
- name: config-fetch-api
  envs: ['fetch_api/config.env']
- name: config-connector-grafana
  envs: ['connectors/grafana/config.env']
- name: config-connector-ml
  envs: ['connectors/ml/config.env']
  