---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fetch-api
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: config-fetch-api
  envs: ['config.env']
