---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: secret-mirrors
  namespace: shared
  labels:
    env: home
spec:
  interval: 1m
  releaseName: secret-mirrors
  chart:
    spec:
      chart: mirrors
      sourceRef:
        kind: HelmRepository
        name: kts
      version: 0.1.9
      interval: 5m0s
