---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: postgresql
  labels:
    app: postgresql
    env: home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
        env: home
    spec:
      containers:
        - name: postgresql
          image: tensorchord/pgvecto-rs:pg15-v0.3.0
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: LSwXeNmwyFe5DsZ
          volumeMounts:
            # - name: postgresql-data
            #   mountPath: /var/lib/postgresql/data
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
      volumes:
        # - name: postgresql-data
        #   persistentVolumeClaim:
        #     claimName: postgresql
        - name: init-scripts
          configMap:
            name: postgresql-initdb
