# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: postgresql
#   namespace: postgresql
#   labels:
#     env: home
# spec:
#   storageClassName: longhorn
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 5Gi
