---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 00-base
  namespace: flux-system
spec:
  suspend: false
  interval: 10m0s
  retryInterval: 30s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: kubernetes/resources/00-base
  prune: true
  wait: true
  timeout: 35m

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 01-prerequisites
  namespace: flux-system
spec:
  suspend: false
  interval: 10m0s
  retryInterval: 30s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: kubernetes/resources/01-prerequisites
  prune: true
  wait: true
  timeout: 35m
  dependsOn:
  - name: 00-base

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 02-dependencies
  namespace: flux-system
spec:
  suspend: false
  interval: 10m0s
  retryInterval: 30s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: kubernetes/resources/02-dependencies
  prune: true
  wait: true
  timeout: 35m
  dependsOn:
  - name: 00-base
  - name: 01-prerequisites

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 03-app-dependencies
  namespace: flux-system
spec:
  suspend: false
  interval: 10m0s
  retryInterval: 30s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: kubernetes/resources/03-app-dependencies
  prune: true
  wait: true
  timeout: 35m
  dependsOn:
  - name: 00-base
  - name: 01-prerequisites
  - name: 02-dependencies

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 04-monitoring
  namespace: flux-system
spec:
  suspend: false
  interval: 10m0s
  retryInterval: 30s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: kubernetes/resources/04-monitoring
  prune: true
  wait: true
  timeout: 35m
  dependsOn:
  - name: 00-base
  - name: 01-prerequisites
  - name: 02-dependencies
  - name: 03-app-dependencies


---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 05-apps
  namespace: flux-system
spec:
  suspend: false
  interval: 10m0s
  retryInterval: 30s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: kubernetes/resources/05-apps
  prune: true
  wait: true
  timeout: 35m
  dependsOn:
  - name: 00-base
  - name: 01-prerequisites
  - name: 02-dependencies
  - name: 03-app-dependencies
  - name: 04-monitoring
