---
apiVersion: v1
kind: Secret
metadata:
  name: auth-longhorn
  namespace: longhorn
  labels:
    env: home
    htpasswd: longhorn
type: Opaque
data:
  auth: c3lzOiRhcHIxJGUwMm0zNG95JFM3TzJpYXZEUEcxcWZqenhzWkxiTDA=
