---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: data-teslamate
  namespace: teslamate
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: home-vault
    kind: ClusterSecretStore
  target:
    name: data-teslamate
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: home/teslamate/data-teslamate
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-teslamate
  namespace: teslamate
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: home-vault
    kind: ClusterSecretStore
  target:
    name: auth-teslamate
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: home/teslamate/auth-teslamate
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
