---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: monitoring
spec:
  interval: 12h
  url: https://charts.bitnami.com/bitnami

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: victoriametrics
  namespace: monitoring
spec:
  interval: 12h
  url: oci://registry-1.docker.io/bitnamicharts/victoriametrics
  ref:
    semver: "0.1.x"

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: kube-state-metrics
  namespace: monitoring
spec:
  interval: 12h
  url: oci://registry-1.docker.io/bitnamicharts/kube-state-metrics
  ref:
    semver: "5.0.x"
