---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: djjudas21
  namespace: jellyfin
  labels:
    env: home
spec:
  interval: 12h
  url: https://djjudas21.github.io/charts/
