---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: loeken-at-home
  namespace: jellyfin
  labels:
    env: home
spec:
  interval: 12h
  url: https://loeken.github.io/helm-charts
