---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: mikeas
  namespace: hostfabtech
  labels:
    env: home
spec:
  interval: 12h
  url: https://mikeas-it.github.io/helm-presta/

