---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: postgres-operator
  namespace: shared
spec:
  interval: 12h
  url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
