---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: data-fetch-api
  namespace: fetch-api
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: home-vault
    kind: ClusterSecretStore
  target:
    name: data-fetch-api
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: home/fetch-api/data-fetch-api
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
