---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetch-api
  namespace: fetch-api
  labels:
    app: fetch-api
    env: home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fetch-api
  template:
    metadata:
      labels:
        app: fetch-api
        env: home
    spec:
      restartPolicy: Always
      imagePullSecrets:
      - name: registry-fetch-api
      containers:
      - name: fetch-api
        image: skullfighter6/fetch-api:0.2.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        command: ["python", "fetch-api.py"]
        args: ["grafana"]
        envFrom:
        - secretRef:
            name: data-fetch-api
