resources:
  requests:
    memory: 128Mi
    cpu: 0.1
  limits:
    memory: 4Gi
    cpu: 4

jellyfin:
  mediaVolumes:
    - name: windows-data
      readOnly: false
      existingClaim: "jellyfin-media-windows-data"
