qbittorrent:
  replicaCount: 1

  strategy:
    type: Recreate

  extraEnv: []
  extraEnvFrom: []

  volumes:
  - name: qbittorrent-windows-data
    persistentVolumeClaim:
      claimName: qbittorrent-windows-data

  volumeMounts:
  - name: qbittorrent-windows-data
    mountPath: /data

  config:
    persistence:
      enabled: true
      size: 5Gi

  ingress:
    enabled: false

  gluetun:
    enabled: false

  prometheusQbittorrentExporter:
    enabled: true

genericDevicePlugin:
  enabled: true
