---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: open-webui
  namespace: open-webui
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-home
    kubernetes.io/ingress.class: nginx                  # home, # Dankata, # Marina / Zhelezhnitsa
    nginx.ingress.kubernetes.io/whitelist-source-range: "92.247.208.224/32,87.243.107.94/32,151.237.55.238/32"
  labels:
    app: open-webui
    env: home
spec:
  tls:
  - hosts:
    - chat.k8s.iaminyourpc.xyz
    secretName: tls-chat-k8s-iaminyourpc-xyz
  rules:
  - host: chat.k8s.iaminyourpc.xyz
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: open-webui
            port:
              number: 80
