---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-initdb
  namespace: immich
  labels:
    env: home
data:
  init.sql: |
    CREATE DATABASE immich;
    CREATE USER immich WITH PASSWORD 'immich';
    GRANT ALL PRIVILEGES ON DATABASE immich TO immich;
    CREATE EXTENSION IF NOT EXISTS cube;
    CREATE EXTENSION IF NOT EXISTS earthdistance;
    CREATE EXTENSION IF NOT EXISTS vectors;"
