---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-kubewall
  namespace: kubewall
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: home-vault
    kind: ClusterSecretStore
  target:
    name: auth-kubewall
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: home/kubewall/auth-kubewall
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
