---
apiVersion: v1
kind: Service
metadata:
  name: krakend
  namespace: krakend
  labels:
    env: home
spec:
  type: ClusterIP
  ports:
  - name: krakend
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: krakend

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: krakend
  namespace: krakend
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-home
    kubernetes.io/ingress.class: nginx                  # home, # Dankata, # Marina/Zhelezhnitsa
    nginx.ingress.kubernetes.io/whitelist-source-range: "10.8.0.0/24,92.247.208.224/32,87.243.107.94/32,151.237.55.238/32"
  labels:
    app: krakend
    env: home
spec:
  tls:
  - hosts:
    - api.k8s.iaminyourpc.xyz
    secretName: tls-api-k8s-iaminyourpc-xyz
  rules:
  - host: api.k8s.iaminyourpc.xyz
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: krakend
            port:
              number: 8080
