---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-qbittorrent
  namespace: qbittorrent
spec:
  refreshInterval: 5m0s
  secretStoreRef:
    name: home-vault
    kind: ClusterSecretStore
  target:
    name: auth-qbittorrent
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: home/qbittorrent/auth-qbittorrent
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
