---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-windows-data
  labels:
    app: qbittorrent
    env: home
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /media/martin/Windows Data
    type: Directory
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-windows-data
  namespace: qbittorrent
  labels:
    app: qbittorrent
    env: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
  storageClassName: manual
  volumeName: qbittorrent-windows-data
