---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shared
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: values-postgresql-shared
  files: ['values.yaml']
