---
apiVersion: v1
kind: Secret
metadata:
  name: auth-pihole
  namespace: monitoring
type: Opaque
data:
  PIHOLE_HOSTNAME: cGlob2xlLXdlYi5waWhvbGUuc3Zj
  PIHOLE_PASSWORD: Y21GVGdXdHZkUUZSM1g3aFhpSUU=
