# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: immich-exporter
#   namespace: monitoring
#   labels:
#     app: immich-exporter
#     env: home
# spec:
#   replicas: 1
#   strategy:
#     type: RollingUpdate
#   selector:
#     matchLabels:
#       app: immich-exporter
#   template:
#     metadata:
#       labels:
#         app: immich-exporter
#         env: home
#     spec:
#       restartPolicy: Always
#       containers:
#       - name: immich-exporter
#         image: eithan1231/immich-exporter:latest
#         imagePullPolicy: IfNotPresent
#         ports:
#         - containerPort: 3000
#         env:
#         - name: IMMICH_HOST
#           valueFrom:
#             secretKeyRef:
#               name: auth-immich
#               key: IMMICH_HOST
#         - name: IMMICH_KEY
#           valueFrom:
#             secretKeyRef:
#               name: auth-immich
#               key: IMMICH_API_KEY
