---
apiVersion: v1
kind: Service
metadata:
  name: pihole-exporter
  namespace: monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9617"
  labels:
    env: home
spec:
  type: ClusterIP
  ports:
  - name: pihole-exporter
    port: 9617
    targetPort: 9617
  selector:
    app: pihole-exporter
