---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-shared
  namespace: shared

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: external-secrets-shared
  namespace: shared
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["authorization.k8s.io"]
  resources: ["selfsubjectrulesreviews"]
  verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: external-secrets-shared
  namespace: shared
subjects:
- kind: ServiceAccount
  name: external-secrets-shared
  namespace: shared
roleRef:
  kind: Role
  name: external-secrets-shared
  apiGroup: rbac.authorization.k8s.io
