---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-operator
  namespace: apps
spec:
  interval: 1m
  releaseName: postgres-operator
  chart:
    spec:
      chart: postgres-operator
      sourceRef:
        name: postgres-operator
        kind: HelmRepository
      reconcileStrategy: ChartVersion
      version: "1.14.0"
      interval: 5m0s
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values: {}
