---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: home-vault
  annotations:
    external-secrets.io/disable-maintenance-checks: "true"
spec:
  provider:
    vault:
      server: "http://vault.vault.svc:8200"
      auth:
        userPass:
          username: external-secrets
          secretRef:
            name: data-vault-sensitive
            key: VAULT_USER_EXTERNAL_SECRETS_PASSWORD
            namespace: vault
