---
apiVersion: v1
kind: Secret
metadata:
  name: auth-capacitor-ui
  namespace: flux-system
  labels:
    env: home
    htpasswd: capacitor-ui
type: Opaque
data:
  auth: c3lzOiRhcHIxJGdsMnQ1bWRpJC8vd0NEZ1hBL0RlS01rbFpDRm9WNzE=
