---
apiVersion: v1
kind: Service
metadata:
  name: capacitor-ui
  namespace: flux-system
  labels:
    helm.sh/chart: onechart-0.69.0
    app.kubernetes.io/name: onechart
    app.kubernetes.io/instance: capacitor-ui
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: onechart
    app.kubernetes.io/instance: capacitor-ui

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: capacitor-ui
  namespace: flux-system
spec:
  policyTypes:
    - Ingress
  ingress:
    - from:
      - namespaceSelector: {}
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: capacitor-ui

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: capacitor-ui
  namespace: flux-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-home
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: auth-capacitor-ui
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
  labels:
    app: capacitor-ui
    env: home
spec:
  tls:
  - hosts:
    - flux.k8s.iaminyourpc.xyz
    secretName: tls-flux-k8s-iaminyourpc-xyz
  rules:
  - host: flux.k8s.iaminyourpc.xyz
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: capacitor-ui
            port:
              number: 9000
