server:
  host: 0.0.0.0
  port: 8080
  assets-path: /app/assets

theme:
  custom-css-file: /assets/user.css

branding:
  app-name: "Home"
  custom-footer: "/ this is my home"

pages:
  - $include: home.yml
