---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-pihole
  namespace: pihole
spec:
  refreshInterval: 5m0s
  secretStoreRef:
    name: home-vault
    kind: ClusterSecretStore
  target:
    name: auth-pihole
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: home/pihole/auth-pihole
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
