vmselect:
  resources:
    requests:
      cpu: 0.1
      memory: 128Mi
    limits:
      cpu: 2
      memory: 2Gi

vminsert:
  resources:
    requests:
      cpu: 0.1
      memory: 128Mi
    limits:
      cpu: 2
      memory: 1Gi
  extraArgs:
  - '--maxLabelsPerTimeseries=200'
  - '--insert.maxQueueDuration=3s'
  - '--maxConcurrentInserts=12'

vmstorage:
  resources:
    requests:
      cpu: 0.1
      memory: 128Mi
    limits:
      cpu: 2
      memory: 2Gi
  persistence:
    enabled: true
    size: 20Gi
  extraArgs:
  - '--retentionPeriod=30d'
  - '--search.maxUniqueTimeseries=300000'
  - '--storage.cacheSizeIndexDBDataBlocks=64MB'
  - '--storage.cacheSizeIndexDBTagFilters=32MB'

vmagent:
  resources:
    requests:
      cpu: 0.2
      memory: 256Mi
    limits:
      cpu: 4
      memory: 4Gi
  extraArgs:
  - '--maxLabelsPerTimeseries=200'
  - '--promscrape.dropOriginalLabels=true'
  - '--memory.allowedPercent=60'
  - '--promscrape.seriesLimitPerTarget=50000'
  existingScrapeConfigMap: config-victoriametrics-jobs

vmauth:
  enabled: false

vmalert:
  enabled: false
