---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetch-api
  namespace: fetch-api
  labels:
    app: fetch-api
    env: home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fetch-api
  template:
    metadata:
      labels:
        app: fetch-api
        env: home
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: registry-fetch-api
      containers:
        - name: fetch-api
          image: ghcr.io/dragon699/home-k8s/fetch-api:0.5.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8069
          command: ["python", "-m", "fetch_api.app"]
          envFrom:
            - secretRef:
                name: data-fetch-api
          env:
            - name: LISTEN_HOST
              value: "0.0.0.0"
            - name: LISTEN_PORT
              value: "8069"
            - name: LOG_FORMAT
              value: "json"
            - name: LOG_LEVEL
              value: "debug"
            - name: OTEL_SERVICE_NAME
              value: "fetch-api"
            - name: OTEL_SERVICE_NAMESPACE
              value: "fetch-api"
            - name: OTEL_SERVICE_VERSION
              value: "0.5.1"
            - name: OTLP_ENDPOINT_GRPC
              value: "grafana-alloy.monitoring.svc:4317"
            - name: CONNECTOR_HEALTH_CHECK_INTERVAL_SECONDS
              value: "60"
            - name: CONNECTOR_HEALTH_RETRY_INTERVAL_SECONDS
              value: "15"
            - name: CONNECTORS
              value: "grafana"
