---
apiVersion: v1
kind: Service
metadata:
  name: fetch-api
  namespace: fetch-api
  labels:
    env: home
spec:
  type: ClusterIP
  ports:
  - name: fetch-api
    port: 8080
    targetPort: 8080
  selector:
    app: fetch-api
