---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cetic
  namespace: immich
  labels:
    env: home
spec:
  interval: 12h
  url: https://cetic.github.io/helm-charts
