# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: mosquitto
#   namespace: teslamate
#   labels:
#     app: mosquitto
#     env: home
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: mosquitto
#   template:
#     metadata:
#       labels:
#         app: mosquitto
#         env: home
#     spec:
#       volumes:
#       - name: mosquitto-data
#         persistentVolumeClaim:
#           claimName: mosquitto-data
#       - name: mosquitto-config
#         persistentVolumeClaim:
#           claimName: mosquitto-config
#       containers:
#       - name: mosquitto
#         image: eclipse-mosquitto:2
#         command: ["mosquitto", "-c", "mosquitto-no-auth.conf"]
#         ports:
#         - containerPort: 1883
#         volumeMounts:
#         - name: mosquitto-data
#           mountPath: /mosquitto/data
#         - name: mosquitto-config
#           mountPath: /mosquitto/config
