---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: glance
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: assets-glance
  files: ['user.css=config/user.css']
- name: config-glance-glance
  files: ['glance.yml=config/glance.yml']
- name: config-glance-home
  files: ['home.yml=config/home.yml']
