---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-windows-data
  labels:
    env: home
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/martin/Windows Data"
    type: Directory
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media-windows-data
  namespace: jellyfin
  labels:
    app: jellyfin
    env: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
  storageClassName: manual
  volumeName: media-windows-data
