---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: config-grafana-alloy
  envs: ['config.env']
- name: pipelines-grafana-alloy
  files: ['alloy.yaml']
