---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: values-longhorn
  files: ['values.yaml']
