apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: redis-shared
  namespace: shared
  labels:
    env: home
spec:
  kubernetesConfig:
    image: quay.io/opstree/redis:latest
    imagePullPolicy: IfNotPresent
    redisSecret:
      name: data-redis-shared
      key: password
  redisExporter:
    enabled: false
    image: quay.io/opstree/redis-exporter:latest
    imagePullPolicy: IfNotPresent
  podSecurityContext:
    fsGroup: 1000
    runAsUser: 1000
  storage:
    volumeClaimTemplate:
      spec:
        accessModes: ['ReadWriteOnce']
        resources:
          requests:
            storage: 10Gi
