---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-gcloud-storage
  namespace: shared
spec:
  refreshInterval: 5m0s
  secretStoreRef:
    name: home-vault
    kind: ClusterSecretStore
  target:
    name: auth-gcloud-storage
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: home/shared/auth-gcloud-storage
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
