name: fetch-api
run-name: Deploy fetch-api

on:
  push:
    paths:
    - '.github/workflows/fetch-api.yaml'
    - 'fetch-api/fetch_api/**'
    - 'fetch-api/common/**'

permissions:
  contents: write
  packages: write

env:
  REGISTRY: ghcr.io
  COMPONENT_NAME: fetch-api
  COMPONENT_PATH: fetch-api/fetch_api
  IMAGE_NAME: dragon699/home-k8s/fetch-api


jobs:

  package:
    runs-on: gha-runner-home

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Authenticate to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Determine Build Version
      id: image_version
      run: echo "VERSION=$(cat ${{ env.COMPONENT_PATH }}/VERSION)" >> $GITHUB_OUTPUT

    - name: Build and Push Image
      uses: docker/build-push-action@v6
      with:
        context: ./${{ env.COMPONENT_NAME }}
        file: ./${{ env.COMPONENT_PATH }}/Dockerfile
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.image_version.outputs.VERSION }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest


  deploy:
    runs-on: gha-runner-home
    needs: package

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Check for yq
      run: |
        echo "Checking for yq installation..."
        which yq || echo "yq not found"
        yq --version || echo "yq command failed"

    # - name: Update ${{ env.COMPONENT_NAME }} manifests
    #   run: 