name: fetch-api
run-name: Deploy fetch-api

on: [push]

permissions:
  contents: read
  packages: write

jobs:
  create_container_image:
    runs-on: gha-runner-home
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v5
    - name: Authenticate to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push Image
      uses: docker/build-push-action@v6
      with:
        context: ./fetch-api
        file: ./fetch-api/fetch_api/Dockerfile
        push: true
        tags: ghcr.io/dragon699/home-k8s/fetch-api/fetch-api:0.5.0
