name: fetch-api-connector-ml
run-name: Deploy connector-ml

on:
  push:
    paths:
    - '.github/workflows/fetch-api-connector-ml.yaml'
    - 'fetch-api/connectors/ml/**'
    - 'fetch-api/common/**'

permissions:
  contents: write
  packages: write

env:
  REGISTRY: ghcr.io
  APP_NAME: fetch-api
  COMPONENT_PATH: fetch-api/connectors/ml
  COMPONENT_DEPLOYMENT_FILE: manifests/apps/fetch-api/connectors/ml/connector-ml.yaml
  IMAGE_NAME: dragon699/home-k8s/fetch-api/connectors/ml


jobs:

  package:
    runs-on: gha-runner-home
    outputs:
      version: ${{ steps.image_version.outputs.VERSION }}

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Authenticate to container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Determine build version
      id: image_version
      run: |
        VERSION_FILE=${{ env.COMPONENT_PATH }}/VERSION
        VERSION=$(cat ${VERSION_FILE})

        if [ $? -ne 0 ] || [ -z "$VERSION" ]; then
          echo "${VERSION_FILE}: Failed to fetch version from file!"

          exit 1
        fi

        echo "VERSION=${VERSION}" >> ${GITHUB_OUTPUT}
        echo "Target image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION}"

    - name: Build and push image
      uses: docker/build-push-action@v6
      with:
        context: ./${{ env.APP_NAME }}
        file: ./${{ env.COMPONENT_PATH }}/Dockerfile
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.image_version.outputs.VERSION }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest


  deploy:
    runs-on: gha-runner-home
    needs: package

    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Update ${{ env.APP_NAME }} manifests
      uses: mikefarah/yq@master
      with:
        cmd: yq -i '.spec.template.spec.containers[0].image = "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.package.outputs.version }}"' ${{ env.COMPONENT_DEPLOYMENT_FILE }}

    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v7
      with:
        commit_message: "connector-ml: Update to v${{ needs.package.outputs.version }}"
        commit_user_name: ActionsBot
        file_pattern: ${{ env.COMPONENT_DEPLOYMENT_FILE }}
