---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: apps
spec:
  interval: 1m
  releaseName: postgresql
  chart:
    spec:
      chart: pg-db
      sourceRef:
        name: percona
        kind: HelmRepository
      reconcileStrategy: ChartVersion
      version: "2.6.0"
      interval: 5m0s
  values:
    postgresVersion: 17
    instances:
      replicas: 1
    users:
      name: apps
      databases: immich,teslamate
