---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant
  namespace: home-assistant
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-home
    kubernetes.io/ingress.class: nginx                  # home, # Dankata, # Marina / Zhelezhnitsa
    nginx.ingress.kubernetes.io/whitelist-source-range: "92.247.208.224/32,87.243.107.94/32,151.237.55.238/32"
  labels:
    app: home-assistant
    env: home
spec:
  tls:
  - hosts:
    - home.k8s.iaminyourpc.xyz
    secretName: tls-home-k8s-iaminyourpc-xyz
  rules:
  - host: home.k8s.iaminyourpc.xyz
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: home-assistant
            port:
              number: 8080
